### ISSUE TITLE
Weather Example Exportability

### ISSUE THREAD

**Issue by tdoughty1** [bokeh/bokeh-demos#21]
Question: Can the functionality demonstrated in the weather demo be exported into a stand-alone html page?

**Comment by bryevdv** [comment]
That example uses functions from `scipy` and `pandas`. In order to not use the server you'd either have to reproduce those computations in JavaScript in `CustomJS` callbacks, or precompute all the data to include in the HTML docs, and switch between the precomputed data in with `CustomJS` callbacks.

**Comment by tdoughty1** [comment]
Ok, thanks for the info.

**Comment by birdsarah** [comment]
@tdoughty1, seems like you got your question answered, I'm going to close this issue. Feel free to re-open, if you need more information, or open a new issue for a new question.
